version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - echo Finished installing source NPM dependencies.
  build:
    commands:
        - echo Build started for environment...
        - ng build --configuration=$ENVIRONMENT
        - echo Finished build.        
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/coffee'